[build-system]
requires = [
    "setuptools >= 61",
    "wheel",
    "numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "didgelab"
version = "3.0.8"
authors = [
  { name = "Jan Nehring", email = "jan.nehring@outlook.com" },
]
description = "Acoustical simulation and computer-aided design of didgeridoos"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
license = { text = "CC BY-NC-SA 4.0" }
dependencies = [
    "configargparse==1.5.3",
    "pandas==1.5.0",
    "scipy==1.10.1",
    "matplotlib==3.6.1",
    "prettytable==3.4.1",
    "seaborn==0.12.0",
    "tqdm==4.67.3",
    "cython==0.29.32",
    "jsonlines==4.0.0",
    "pytest==8.3.5",
    "scikit-fem==10.0.2",
    "build==1.4.0",
    "twine==6.2.0",
    "setuptools==82.0.0"
]

[project.urls]
Homepage = "https://github.com/didgitaldoo/didge-lab"
Issues = "https://github.com/didgitaldoo/didge-lab/issues"

[tool.setuptools.packages.find]
where = ["src"]
