[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "didgelab"
version = "2.0"
authors = [
  { name="Jan Nehring", email="jan.nehring@outlook.com" },
]
description = "Mathematical simulation of Didgeridoos"
readme = "README.md"
requires-python = "=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GNU GPL v2"
license-files = ["LICENSE.txt"]

[project.urls]
Homepage = "https://github.com/didgitaldoo/didge-lab"
Issues = "https://github.com/didgitaldoo/didge-lab/issues"
